django_proj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('forms/', include('form_app.urls')),
]

form_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('done', views.SubmissionSuccessView.as_view(), name='submission_success'),
    path('test_form', views.EmployeeFormView.as_view(), name='test_form')
]

form_app/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

from form_app.validators import validate_file_size


class EmployeeTestModel(models.Model):
    """This is the model which is used to save the form data into the DB"""

    full_name = models.CharField(max_length=50)
    post_code = models.CharField(max_length=8, blank=True)
    last_salary = models.IntegerField(default=0)
    uk_resident = models.BooleanField(default=False)
    resume_file = models.FileField(
        upload_to='media/',
        validators=[FileExtensionValidator(allowed_extensions=['pdf']), validate_file_size]
    )

form_app/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from ukpostcodeutils import validation

from form_app.models import EmployeeTestModel


class EmployeeTestForm(forms.ModelForm):
    error_css_class = 'error'

    class Meta:
        model = EmployeeTestModel
        fields = '__all__'
        widgets = {
            'full_name': forms.TextInput(attrs={'placeholder': u'Full Name'}),
        }
        help_texts = {
            'last_salary': 'Yearly, in GBP (£)'
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeTestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = True
        self.helper.form_id = 'form-test'
        self.helper.form_class = 'uniForm'
        self.helper.form_method = 'POST'
        self.helper.form_action = '/forms/done'
        self.helper.form_show_errors = True
        self.helper.attrs = {'novalidate': True}

        self.fields['post_code'].widget.attrs = {'id': 'p_code', 'required': False}
        self.fields['uk_resident'].widget.attrs = {'onclick': 'showHidePostcode()'}
        self.fields['uk_resident'].label = 'Are you currently a UK resident?'

    def clean(self):
        """This method has been overridden to perform our custom validation on certain fields"""

        cleaned_data = super(EmployeeTestForm, self).clean()

        post_code = str(self.cleaned_data.get('post_code', None))
        if post_code:
            if not validation.is_valid_postcode(post_code.replace(' ', '')):
                self._errors["post_code"] = ["Please enter a valid UK postcode (eg NW7 1GH)"]
                del self.cleaned_data['post_code']

        full_name = str(cleaned_data.get('full_name', ''))
        if len(full_name.split(' ')) != 2:
            self._errors["full_name"] = ["Please enter a full name (first and last)"]
            del self.cleaned_data['full_name']

        salary = cleaned_data.get('last_salary', 0)
        if salary < 0:
            self._errors["last_salary"] = ["Please enter a value greater than or equal to 0"]
            del self.cleaned_data['last_salary']

        return cleaned_data

form_app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, FormView

from form_app.forms import EmployeeTestForm


class SubmissionSuccessView(View):
    """This view serves the success message when the form has been submitted"""

    template_name = 'form_app/success.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class EmployeeFormView(FormView):
    """This is the view that serves the form for the app"""

    form_class = EmployeeTestForm
    template_name = 'form_app/form.html'
    success_url = reverse_lazy('submission_success')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form})

form_app/templates/form_app/base.html
<!doctype html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load staticfiles %}
    <link href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'static_jquery/js/jquery.js' %}"></script>

    <title>Test form</title>

    <script type="text/javascript">
        function hidePostcode() {
            var checkbox = document.getElementById("id_uk_resident");
            if (checkbox.checked === false) {
                document.getElementById("p_code").setAttribute("type", "hidden");
                console.log(document.getElementsByClassName("col-form-label")[1].className);
                document.getElementsByClassName("col-form-label")[1].setAttribute("style", "display: none;");
            }
        }
    </script>

</head>
<body onload="hidePostcode()">
<div class="container d-flex h-100">
    <div class="row justify-content-center">
        <div class="col-20">
            <h5> Please fill out the following form </h5>
            {% block main %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

form_app/templates/form_app/form.html
<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.0.min.js"></script>
<script type="text/javascript">

    function showHidePostcode() {

        var checkbox = document.getElementById("id_uk_resident");

        if (checkbox.checked === true) {
            document.getElementById("p_code").removeAttribute("type");
            console.log('hidden removed');
            document.getElementsByClassName("col-form-label")[1].removeAttribute("style");
        } else {
            document.getElementById("p_code").setAttribute("type", "hidden");
            document.getElementsByClassName("col-form-label")[1].setAttribute("style", "display: none;");
        }


    }


</script>

{% extends 'form_app/base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.full_name|as_crispy_field }}
        {{ form.uk_resident|as_crispy_field }}
        {{ form.post_code|as_crispy_field }}
        {{ form.last_salary|as_crispy_field }}

        <label for="id_resume_file" class="col-form-label  requiredField">
            CV / Cover Letter<span class="asteriskField">*</span>
        </label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">Upload</span>
            </div>
            <div class="custom-file">
                <input name="resume_file" type="file" class="custom-file" id="id_resume_file">
                <label class="custom-file-label" for="id_resume_file">Choose file</label>
            </div>
        </div>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirm_submit">
            Submit
        </button>


        <!-- Modal -->
        <div class="modal fade" id="confirm_submit" tabindex="-1" role="dialog" aria-labelledby="confirm_submit_label"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirm_submit_label">Are you sure you want to submit?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

form_app/templates/form_app/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submitted Successfully</title>
</head>
<body>
    <p>Form submitted successfully</p>
</body>
</html>